# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d979220d4678e4b79297b512913b48d6f67c030821360b4c9b8884bdaa790850ac6a6d70bd89a4f20033fb6d6a11cd884300023f506b93b09f012d10b9e2e187

test:
  secret_key_base: 435e8027753c94d4c537e86c8cb7f90874f77646eecd8100c6df169fbe5fddfa25633d50dc079b03e5856f3d4a040598e2ceee439e4e4e2c800ffa265bf11b16

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
